### ISSUE TITLE
Prediction with Dataset3DSimple 'image_only' missing

### ISSUE THREAD

**Issue by LangDaniel** [mazurowski-lab/3D-Breast-FGT-and-Blood-Vessel-Segmentation#1]
Hi,  
wanted to test `prediction.py` with the TCIA data, but couldn't get it to run.
How is the `Dataset3DSimple` module supposed to work in the prediction case?
The specified `image_only` variable is not given in the `Dataset3DSimple`, or?
How can you use `Dataset3DSimple` with no ground truth data available? 

Best,
Daniel

**Comment by chris-lew** [comment]
Hi Daniel,
Thanks for pointing that out. Looks like I accidentally used an older version of the dataset file. It's been updated. Let me know if you still have issues.
