### ISSUE TITLE
function arguments in wrong order

### ISSUE THREAD

**Issue by FSchwarzhans** [mazurowski-lab/3D-Breast-FGT-and-Blood-Vessel-Segmentation#3]
The arguments passed in the function `pred_and_save_masks_3d_simple` appear to be in the wrong order, also argument `n_channels` is expected by the function but not passed.
https://github.com/mazurowski-lab/3D-Breast-FGT-and-Blood-Vessel-Segmentation/blob/232c462f4761b87125a9c58717360db859dc5b87/predict.py#L78C8-L84C10

**Comment by chris-lew** [comment]
Updated, thank you
