### ISSUE TITLE
The sequence  for the input image

### ISSUE THREAD

**Issue by shigen-StoneRoot** [mazurowski-lab/3D-Breast-FGT-and-Blood-Vessel-Segmentation#4]
Thanks for your great work. I want to know which sequence is used for the input image.

For example, the 'Breast_MRI_025' contains 5 data, with a description as 
```
'ax t1 3mm'
'ax 3d dyn'
'Ph1/ax 3d dyn'
'Ph2/ax 3d dyn'
'Ph3/ax 3d dyn'
```

I'm unsure which one fits your paper's description: ‘ T1-weighted fat-suppressed pre-contrast sequence’.

I would be grateful if you could reply to it.

**Comment by chris-lew** [comment]
`'ax 3d dyn'` is the proper sequence in this case. Please see the TCIA website to help determine which sequence to use, there is a file mapping csv that maps sequences to directories.
